class BookModel {
  final String image;
  final String name;
  final String? writer;
  final String? drawer;
  final double? price;
  final double? priceAfetDiscount;
  final int? discountPerCent;
  final String? description;
  final String? pageNumber;
  final String? size;

  BookModel({
    required this.image,
    required this.name,
    this.writer,
    this.drawer,
    this.price,
    this.priceAfetDiscount,
    this.discountPerCent,
    this.description,
    this.pageNumber,
    this.size,
  });
}

String masumlarDescription =
    """Bu seri çocuklarimiza Hz. Muhammed (s.a.a) ve Ehl-i Beyt'in hayatini anlatmaktadir. Cocuklarimiz için hazirlanan 14 farkli kitap: sade, eglenceli ve gretici bir dille yazilmis ve anlatilan konularin gocuklarin zihninde
yer edinmesi amaclyla hikayelere uygun olarak resimler sizilmistir. Çocuklar kitaplari okurken o dönemi kendi zihin dünyalarinda canlandiracak ve bu büyük sahsiyetlerle daha lyi bir bag kurabileceklerdir.
Kitaplari okuyup bitiren gocuklarimizin ögrendiklerini degerlendirmeleri için Hekimane Soru Kitapligi mobil uygulamasi da kullanima sunulmustur.
Yenilikçi bir vizyonla hazirlanan bu uygulamayi kitaplarin arka sayfalarinda yer alan karekoduyla indirerek her kitap için hazirlanan sorulari cevaplayabilir ve puanlarini görebilirler.""";
String masumlarPageNumber = "Kuşe Kağıt";
String masumlarSize = "17 * 24";
String peygamberlerDescription =
    """Allah'in biz kullar için tarih boyunca ozel olarak sectigi insanlar, peygamberlerdir. Peygamberlerin Hayati adli seride bu özel insanlarin hayati anlatilmaktadir.
Cocuklarin, insanlari kurtulusa ve ilahi davete cagiran peygamberlerin hayatini okumasi, kisiliklerinin olumlu yönde gelismesine nemli katki saglar. Kitaplarda anlatilan hikayeler, özel tekniklerle cizilmis resimlerle süslenmistir. Bu nedenle kitaplari okuyan ocuklar kendilerini hikayelerin içinde bulacaktir.
Kitaplari okuyup bitiren ocuklarimizin ögrendiklerini degerlendirmeleri için Hekimane Soru Kitapligi mobil uygulamasi da kullanima sunulmustur.
Yenilikçi bir vizyonla hazirlanan bu uygulamayi kitaplarin arka sayfalarinda yer alan karekoduyla indirerek her kitap için hazirlanan sorulari cevaplayabilir ve puanlarini görebilirler""";
String peygamberlerPageNumber = "16 sayfa - Kuşe Kağıt";
String peygamberlerSize = "16 * 24";

double price1 = 60;
double priceAfetDiscount1 = 40;
int discountPerCent1 = 30;

double price2 = 80;
double priceAfetDiscount2 = 55;

List<BookModel> masumlarBookList = [
  BookModel(
    image: 'assets/img/kitaplar/masumlar',
    name: "Hz. Muhammed (s.a.a)",
    writer: "Zehra Abdi",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    description: masumlarDescription,
    pageNumber: masumlarPageNumber,
    size: masumlarSize,
  ),
  BookModel(
    image: 'assets/img/kitaplar/masumlar',
    name: "Hz. Fatıma (s.a)",
    writer: "Zehra Abdi",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    description: masumlarDescription,
    pageNumber: masumlarPageNumber,
    size: masumlarSize,
  ),
  BookModel(
    image: 'assets/img/kitaplar/masumlar',
    name: "Hz. Ali (a.s)",
    writer: "Zehra Abdi",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    description: masumlarDescription,
    pageNumber: masumlarPageNumber,
    size: masumlarSize,
  ),
  BookModel(
    image: 'assets/img/kitaplar/masumlar',
    name: "Hz. Hasan (a.s)",
    writer: "Zehra Abdi",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    description: masumlarDescription,
    pageNumber: masumlarPageNumber,
    size: masumlarSize,
  ),
  BookModel(
    image: 'assets/img/kitaplar/masumlar',
    name: "Hz. Hüseyin (a.s)",
    writer: "Zehra Abdi",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    description: masumlarDescription,
    pageNumber: masumlarPageNumber,
    size: masumlarSize,
  ),
  BookModel(
    image: 'assets/img/kitaplar/masumlar',
    name: "Hz. Zeynel Abidin (a.s)",
    writer: "Zehra Abdi",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    description: masumlarDescription,
    pageNumber: masumlarPageNumber,
    size: masumlarSize,
  ),
  BookModel(
    image: 'assets/img/kitaplar/masumlar',
    name: "Hz. Muhammed Bakır (a.s)",
    writer: "Zehra Abdi",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    description: masumlarDescription,
    pageNumber: masumlarPageNumber,
    size: masumlarSize,
  ),
  BookModel(
    image: 'assets/img/kitaplar/masumlar',
    name: "Hz. Cafer-i Sadık (a.s)",
    writer: "Zehra Abdi",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    description: masumlarDescription,
    pageNumber: masumlarPageNumber,
    size: masumlarSize,
  ),
  BookModel(
    image: 'assets/img/kitaplar/masumlar',
    name: "Hz. Musa Kazım (a.s)",
    writer: "Zehra Abdi",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    description: masumlarDescription,
    pageNumber: masumlarPageNumber,
    size: masumlarSize,
  ),
  BookModel(
    image: 'assets/img/kitaplar/masumlar',
    name: "Hz. Ali Rıza (a.s)",
    writer: "Zehra Abdi",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    description: masumlarDescription,
    pageNumber: masumlarPageNumber,
    size: masumlarSize,
  ),
  BookModel(
    image: 'assets/img/kitaplar/masumlar',
    name: "Hz. Muhammed Taki (a.s)",
    writer: "Zehra Abdi",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    description: masumlarDescription,
    pageNumber: masumlarPageNumber,
    size: masumlarSize,
  ),
  BookModel(
    image: 'assets/img/kitaplar/masumlar',
    name: "Hz. Ali Naki (a.s)",
    writer: "Zehra Abdi",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    description: masumlarDescription,
    pageNumber: masumlarPageNumber,
    size: masumlarSize,
  ),
  BookModel(
    image: 'assets/img/kitaplar/masumlar',
    name: "Hz. Hasan Askeri (a.s)",
    writer: "Zehra Abdi",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    description: masumlarDescription,
    pageNumber: masumlarPageNumber,
    size: masumlarSize,
  ),
  BookModel(
    image: 'assets/img/kitaplar/masumlar',
    name: "Hz. Mehdi (a.f)",
    writer: "Zehra Abdi",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    description: masumlarDescription,
    pageNumber: masumlarPageNumber,
    size: masumlarSize,
  ),
];

List<BookModel> peygamberlerBookList = [
  BookModel(
    image: 'assets/img/kitaplar/peygamberler',
    name: "Hz. Adem (a.s)",
    writer: "İbrahim Hasan Beygi",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    drawer: "Hasan Ammekon",
    description: peygamberlerDescription,
    pageNumber: peygamberlerPageNumber,
    size: peygamberlerSize,
  ),
  BookModel(
    image: 'assets/img/kitaplar/peygamberler',
    name: "Hz. Nuh (a.s)",
    writer: "İbrahim Hasan Beygi",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    drawer: "Hasan Ammekon",
    description: peygamberlerDescription,
    pageNumber: peygamberlerPageNumber,
    size: peygamberlerSize,
  ),
  BookModel(
    image: 'assets/img/kitaplar/peygamberler',
    name: "Hz. Salih (a.s)",
    writer: "İbrahim Hasan Beygi",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    drawer: "Hasan Ammekon",
    description: peygamberlerDescription,
    pageNumber: peygamberlerPageNumber,
    size: peygamberlerSize,
  ),
  BookModel(
    image: 'assets/img/kitaplar/peygamberler',
    name: "Hz. İdris (a.s)",
    writer: "İbrahim Hasan Beygi",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    drawer: "Hasan Ammekon",
    description: peygamberlerDescription,
    pageNumber: peygamberlerPageNumber,
    size: peygamberlerSize,
  ),
  BookModel(
    image: 'assets/img/kitaplar/peygamberler',
    name: "Hz. Süleyman (a.s)",
    writer: "İbrahim Hasan Beygi",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    drawer: "Hasan Ammekon",
    description: peygamberlerDescription,
    pageNumber: peygamberlerPageNumber,
    size: peygamberlerSize,
  ),
  BookModel(
    image: 'assets/img/kitaplar/peygamberler',
    name: "Hz. İbrahim (a.s)",
    writer: "İbrahim Hasan Beygi",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    drawer: "Hasan Ammekon",
    description: peygamberlerDescription,
    pageNumber: peygamberlerPageNumber,
    size: peygamberlerSize,
  ),
  BookModel(
    image: 'assets/img/kitaplar/peygamberler',
    name: "Hz. Yunus (a.s)",
    writer: "İbrahim Hasan Beygi",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    drawer: "Hasan Ammekon",
    description: peygamberlerDescription,
    pageNumber: peygamberlerPageNumber,
    size: peygamberlerSize,
  ),
  BookModel(
    image: 'assets/img/kitaplar/peygamberler',
    name: "Hz. Eyyub (a.s)",
    writer: "İbrahim Hasan Beygi",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    drawer: "Hasan Ammekon",
    description: peygamberlerDescription,
    pageNumber: peygamberlerPageNumber,
    size: peygamberlerSize,
  ),
  BookModel(
    image: 'assets/img/kitaplar/peygamberler',
    name: "Hz. Yusuf (a.s)",
    writer: "İbrahim Hasan Beygi",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    drawer: "Hasan Ammekon",
    description: peygamberlerDescription,
    pageNumber: peygamberlerPageNumber,
    size: peygamberlerSize,
  ),
  BookModel(
    image: 'assets/img/kitaplar/peygamberler',
    name: "Hz. Musa (a.s)",
    writer: "İbrahim Hasan Beygi",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    drawer: "Hasan Ammekon",
    description: peygamberlerDescription,
    pageNumber: peygamberlerPageNumber,
    size: peygamberlerSize,
  ),
  BookModel(
    image: 'assets/img/kitaplar/peygamberler',
    name: "Hz. İsa (a.s)",
    writer: "İbrahim Hasan Beygi",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    drawer: "Hasan Ammekon",
    description: peygamberlerDescription,
    pageNumber: peygamberlerPageNumber,
    size: peygamberlerSize,
  ),
  BookModel(
    image: 'assets/img/kitaplar/peygamberler',
    name: "Hz. Muhammed (s.a.a)",
    writer: "İbrahim Hasan Beygi",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    drawer: "Hasan Ammekon",
    description: peygamberlerDescription,
    pageNumber: peygamberlerPageNumber,
    size: peygamberlerSize,
  ),
];

List<BookModel> otherBookList = [
  BookModel(
    image: 'assets/img/kitaplar/allahinGuzelIsimleri.jpeg',
    name: "Allahın Güzel İsimleri",
    writer: "Celil Zengin",
    price: 70,
    priceAfetDiscount: 50,
    discountPerCent: discountPerCent1,
    drawer: "Leyla Purmuhammedi",
    pageNumber: "32 Sayfa - Kuşe Kağıt",
    size: "16 * 22",
    description:
        """"Allah, kendisinden baska ilâh olmayandir. En güzel isimler O'na mahsustur." Kuran-1 Kerim, Taha Suresi, 8. ayet Hazirladigimiz bu kitapta Allah'in güzel isimlerini sade ve akici hikâyelerle ocuklara gretmeyi amaçladik. Cocuklar, resimlerle süslenen hikâyeleri okuyarak, Allah' in 15 farkli ismini akilda kalacak sekilde ogrenmis olacaklar.""",
  ),
  BookModel(
    image: 'assets/img/kitaplar/benimGuzelNamazım.jpeg',
    name: "Benim Güzel Namazım",
    writer: "Celil Zengin",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    drawer: "Fereste Erkiya",
    pageNumber: "32 Sayfa - Kuşe Kağıt",
    size: "16 * 21",
    description:
        """Peygamber Efendimiz Hz. Muhammed (s.a.a): "Namaz dinin sütunudur." diye buyurmustur. Nasil sütunlar binalari korur ve onlarin ayakta durmasini saglarsa, namaz da dini muhafaza ederek insani korur ve mutlu olmasini saglar. Bu kitabimizda namazin önemini ve kilinisini ayni zamanda abdestin alinisini ogrenecegiz.""",
  ),
  BookModel(
    image: 'assets/img/kitaplar/dogruYolaDavet.jpeg',
    name: "Doğru Yola Davet",
    writer: "İbrahim Hasan Beygi",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    drawer: "Negin Hüseyinzade",
    pageNumber: "24 Sayfa - Kuşe Kağıt",
    size: "17 * 24",
    description:
        """Allah Resulü Hz. Muhammed (s.a.a) Medine'de oldugu yillarda dünyanin dort bir yanindaki devlet baskanlarina ve dini merkezlere elçiler gönderip, mektuplar yazarak insanlari Islam'a davet ediyordu.
Necran'a da bir elçi göndererek onlari Islam'a davet etti. Necran baspapazi Ebu Haris, Hz. Muhammed'in (s.a.a) mektubunu alinca bir heyetle beraber Medine'ye giderek onunla (s.a.a) görüstü. Hristiyan heyet,
Allah Resulü'nün mantikli sözlerini kabul etmedi. Ardindan Allah, Resulullah'a (s.a.a) onlarla mübahele etmesini emretti.
Bu önemli olayin hikayesini, usta yazar Ibrahim Hasan Beygi'nin kalemi ve cocuk ressami Negin Hüseyinzade'nin cizimleriyle bu kitapta çocuklarla
bulusturduk.""",
  ),
  BookModel(
    image: 'assets/img/kitaplar/hzZeynep.jpeg',
    name: "Hz. Zeyneb (s.a)",
    writer: "Cemkeran Araştırma Bölümü",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
  ),
  BookModel(
    image: 'assets/img/kitaplar/gadirHum.jpeg',
    name: "Gadir Hum Bayramı",
    writer: "Seyyid Muhammed Muhacirani",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    drawer: "Vecihe Gulmezari",
    pageNumber: "24 Sayfa - Kuşe Kağıt",
    size: "17 * 24",
    description:
        """Gadir Hum, Mekke-Medine yolu üzerinde "Hum" denilen bir yerdeki göletin adidir. Hicretin 10. yilinin Zilhicce ayinin on sekizinde
Hz. Muhammed (s.a.a) bu yerde Hz. All'yi (a.s) kendisinden sonra halife ve veli olarak tayin etmistir. Cocuklar için hazirladigimiz bu kitabimizda söz konusu önemli olayin hikâyesi anlatilmaktadir.""",
  ),
  BookModel(
    image: 'assets/img/kitaplar/hzAbbas.jpeg',
    name: "Hz. Abbas (a.s)",
    writer: "Celil Zengin",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
  ),
  BookModel(
    image: 'assets/img/kitaplar/hzHamza.jpeg',
    name: "Hz. Hamza (a.s)",
    writer: "Mecid Muhammedi",
    price: price2,
    priceAfetDiscount: priceAfetDiscount2,
    discountPerCent: discountPerCent1,
  ),
  BookModel(
    image: 'assets/img/kitaplar/veyselKarani.jpeg',
    name: "Veysel Karani",
    writer: "Mecid Muhammedi",
    price: 80,
    priceAfetDiscount: 55,
    discountPerCent: discountPerCent1,
  ),
  BookModel(
    image: 'assets/img/kitaplar/hzMehdiSorular.jpeg',
    name: "Hz. Mehdi (a.f) ve Sorulara Cevaplar",
    writer: "Ali Şaibi",
    price: 100,
    priceAfetDiscount: 70,
    discountPerCent: 30,
    drawer: "Atife Fettuhi",
    pageNumber: "80 Sayfa - Kuşe Kağıt",
    size: "14 * 21",
    description:
        """Bu kitapta zamanimizin imami Hz. Mendinin (a.s) hayati, gaybeti ve zuhuru hakkinda bilgi sahibi olacagimiz gibi, onunla görüsme serefine erisenlerin
hikayelerini de okuyacagiz. Bu kitaptaki cevaplarin çogu,
kitaplarda yer alan Hz. Mehdinin (a.s) hayatiyla ilgili
meshur hadislerden alinmistir. Kitap, kolay okunmasi için sade ve akici bir dille hazirlanmistir.""",
  ),
  BookModel(
    image: 'assets/img/kitaplar/hzMuhammedVeDeveleri.jpeg',
    name: "Hz. Muhammed (s.a.a) ve Develeri",
    writer: "Heda Haşmetiyan",
    price: 120,
    priceAfetDiscount: 80,
    discountPerCent: discountPerCent1,
  ),
  BookModel(
    image: 'assets/img/kitaplar/hzNergis.jpeg',
    name: "Benim En Değerli Misafirim",
    writer: "Turan Saki",
    price: 100,
    priceAfetDiscount: 70,
    discountPerCent: discountPerCent1,
    drawer: "Seher Saderat",
    pageNumber: "44 Sayfa - Kuşe Kağıt",
    size: "17 * 24",
    description:
        """Benim En Degerli Misafirim kitabi, Tahtal isimli eski bir geminin maceral yolculuju ile bagliyor. Tahtal eski bir gemi olduju isin
fazla yolcusu yoktur. Geng ve yeni gemiler her zaman Tahtali ile dalga geçer. Tahtal kaptanin hasta kizi için higbir sey yapamadigi için üzülür. Bir gece baliklar ve Sevgili Ay, Tahtali nin üzgün
oldugunu görünce yakinda ok önemli bir misafirin onunla yolculuga
Sikacagini haber ederler. Bu degerli yolcu, gefkatli Nergis
Hatun' dur.""",
  ),
  BookModel(
    image: 'assets/img/kitaplar/iyilerinKissasi.jpeg',
    name: "İyilerin Kıssası",
    writer: "Mecid Molla Muhammedi",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    drawer: "Negin Hüseyinzade",
    pageNumber: "24 Sayfa - Kuşe Kağıt",
    size: "17 * 24",
    description: """Kisa Hadisi,
Allah Resulü Hz. Muhammed (s.a.a), Hz. Ali (a.s), Hz. Fatima (s.a), Hz. Hasan (a.s) ve Hz. Huseyin'in (a.s) fazileti hakkinda
önemli bir hadistir.
Bu kitapta söz konusu hadis ve yasanan olay, usta yazar Mecid Molla Muhammedinin kalemi ve Negin Hüseyinzade'nin fizimleriyle anlatilmaktadir.
Çocuklar bu kitabi okuyarak Hz. Muhammed (s.a.a) ve Ehlibeyt'iyle (a.s) yakinlik kuracak ve manevi yönlerini
gelistirecekler.""",
  ),
  BookModel(
    image: 'assets/img/kitaplar/karBeyaz.jpeg',
    name: "Kar Beyaz, Tonton ve Bilge Dede",
    writer: "Hüseyin Yazıcıoğlu",
    price: 120,
    priceAfetDiscount: 80,
    discountPerCent: 30,
  ),
  BookModel(
    image: 'assets/img/kitaplar/kerbeladaBirGuvercin.jpeg',
    name: "Kerbelada Bir Güvercin",
    writer: "Celil Zengin",
    drawer: "İlahe Sadıkıyan",
    price: price1,
    priceAfetDiscount: priceAfetDiscount1,
    discountPerCent: discountPerCent1,
    pageNumber: "32 Sayfa - Kuşe Kağıt",
    size: "16 * 22",
    description: """
    Kerbela'da Bir Güvercin
    Hicretin 61. yilinda gerçeklesen Kerbela olayinda sevgili peygamberimiz Hz. Muhammed' in (s.a.a) biricik torunu Hz. Hüseyin
    (a.s) ve ailesi, Yezid ve askerleri tarafindan sehit edildi. O tarihten beri tüm Müslümanlarin kalbinde asla dinmeyen bir hüzün olustu.
    Bu nedenle her yil bu aci olay, Muslumanlar arasinda matem merasimleriyle canli tutulmaktadir.
    iste bu önemli olayi cocuklarimiza sade bir dille anlatmak için bu eser kaleme alinarak resimlerle süslendi.
    """,
  ),
  BookModel(
    image: 'assets/img/kitaplar/sihirliSilgi.jpeg',
    name: "Sihirli Silgi",
    writer: "Leyla Ahlaki",
    price: 80,
    priceAfetDiscount: 55,
    discountPerCent: discountPerCent1,
    pageNumber: "24 Sayfa - Kuşe Kağıt",
    size: "23 * 23",
  ),
  BookModel(
    image: 'assets/img/kitaplar/other/haylaz_hindiba.jpeg',
    name: "Haylaz Hindiba",
    writer: "Muhammed Muhacirniya",
    price: 80,
    priceAfetDiscount: 60,
    discountPerCent: 25,
    pageNumber: "24 Sayfa - Kuşe Kağıt",
    size: "22 * 22",
  ),
  BookModel(
    image: 'assets/img/kitaplar/other/hayalci_serce.jpeg',
    name: "Hayalci Serçe",
    writer: "Muhammed Muhacirniya",
    price: 80,
    priceAfetDiscount: 60,
    discountPerCent: 25,
    pageNumber: "24 Sayfa - Kuşe Kağıt",
    size: "22 * 22",
  ),
  BookModel(
    image: 'assets/img/kitaplar/other/benekli.jpeg',
    name: "Benekli ile Hallı",
    writer: "Muhammed Muhacirniya",
    price: 80,
    priceAfetDiscount: 60,
    discountPerCent: 25,
    pageNumber: "24 Sayfa - Kuşe Kağıt",
    size: "22 * 22",
  ),
  BookModel(
    image: 'assets/img/kitaplar/other/kaku_ile_kuku.jpeg',
    name: "Kaku ile Kuku",
    writer: "Muhammed Muhacirniya",
    price: 80,
    priceAfetDiscount: 60,
    discountPerCent: 25,
    pageNumber: "24 Sayfa - Kuşe Kağıt",
    size: "22 * 22",
  ),
  BookModel(
    image: 'assets/img/kitaplar/other/komik_karga.jpeg',
    name: "Komik Karga",
    writer: "Muhammed Muhacirniya",
    price: 80,
    priceAfetDiscount: 60,
    discountPerCent: 25,
    pageNumber: "24 Sayfa - Kuşe Kağıt",
    size: "22 * 22",
  ),
  BookModel(
    image: 'assets/img/kitaplar/other/kisa_kuyruk.jpeg',
    name: "Kısa Kuyruk",
    writer: "Muhammed Muhacirniya",
    price: 80,
    priceAfetDiscount: 60,
    discountPerCent: 25,
    pageNumber: "24 Sayfa - Kuşe Kağıt",
    size: "22 * 22",
  ),
  BookModel(
    image: 'assets/img/kitaplar/other/nergisin_bekleyisi.jpeg',
    name: "Nergis'in Bekleyişi",
    writer: "Hüseyin Mücahid",
    price: 80,
    priceAfetDiscount: 60,
    discountPerCent: 25,
    pageNumber: "24 Sayfa - Kuşe Kağıt",
    size: "22 * 22",
  ),
  BookModel(
    image: 'assets/img/kitaplar/nur_evi.jpeg',
    name: "Nur Evi",
    writer: "Zehra Abdi",
    drawer: "Fahte Şemsevi",
    price: 80,
    priceAfetDiscount: 55,
    discountPerCent: 30,
    pageNumber: "24 Sayfa - Kuşe Kağıt",
    size: "22 * 22",
  ),
  BookModel(
    image: 'assets/img/kitaplar/oyuncak_dukkani.jpeg',
    name: "Oyuncak Dükkanı",
    writer: "Muna Cevan",
    drawer: "Şadi Dilpak",
    price: 80,
    priceAfetDiscount: 55,
    discountPerCent: 30,
    pageNumber: "28 Sayfa - Kuşe Kağıt",
    size: "19 * 26",
  ),
  BookModel(
    image: 'assets/img/kitaplar/ciflikteki_macera.jpeg',
    name: "Çiflikteki Macera",
    writer: "Zeynep Şehristani",
    drawer: "Mehsa Velizade",
    price: 80,
    priceAfetDiscount: 55,
    discountPerCent: 30,
    pageNumber: "28 Sayfa - Kuşe Kağıt",
    size: "22 * 22",
  ),
  BookModel(
    image: 'assets/img/kitaplar/buyuk_babamin_beyaz_kalbi.jpeg',
    name: "Büyük Babamın Beyaz Kalbi",
    writer: "Müslim Nasıri",
    drawer: "Esel Neccari",
    price: 80,
    priceAfetDiscount: 60,
    discountPerCent: 25,
    pageNumber: "28 Sayfa - Kuşe Kağıt",
    size: "19 * 26",
  ),
  BookModel(
    image: 'assets/img/kitaplar/hz_fatimanin_hayatindan_hikayeler.jpeg',
    name: "Hz. Fatıma'nın Hayatından Hikayeler",
    writer: "Mecid Muhammedi",
    drawer: "Merziye Givamzade",
    price: 80,
    priceAfetDiscount: 55,
    discountPerCent: 30,
    pageNumber: "48 Sayfa - Kuşe Kağıt",
    size: "19 * 24",
  ),
  BookModel(
    image: 'assets/img/kitaplar/asik_hurma_saticisi.jpeg',
    name: "Aşık Hurma Satıcısı",
    writer: "Mecid Muhammedi",
    price: 80,
    priceAfetDiscount: 55,
    discountPerCent: 30,
    pageNumber: "52 Sayfa",
    size: "13 * 19",
  ),
  BookModel(
    image: 'assets/img/kitaplar/hz_alinin_yoldasi.jpeg',
    name: "Hz. Ali'nin Yoldaşı",
    writer: "Mecid Muhammedi",
    price: 80,
    priceAfetDiscount: 55,
    discountPerCent: 30,
    pageNumber: "48 Sayfa",
    size: "13 * 19",
  ),
];
