import 'dart:convert';

import '../view/models/category.dart';
import '../view/models/question.dart';

const String baseUrl = "https://opentdb.com/api.php";

Future<List<Question>> getQuestions(Category category) async {
  List<Map<String, dynamic>> questions = [];
  questions = List<Map<String, dynamic>>.from(json.decode(Sorular[category.id - 1])["results"]);

  return Question.fromData(questions);
}

List<String> Sorular = [
  json1,
  json2,
  json3,
  json4,
  json5,
  json6,
  json7,
  json8,
  json9,
  json10,
  json11,
  json12,
  json13,
  json14
];

var json1 = "{\"response_code\":0,\"results\":[{"
    "\"category\":\"Hz. Muhammed\","
    "\"type\":\"multiple\","
    "\"difficulty\":\"easy\","
    "\"question\":\"Hz. Muhammed'in(saa) annesinin ve babasının adları nedir?\","
    "\"correct_answer\":\"Abdullah ve Amine️\","
    "\"incorrect_answers\":[\"İbrahim ve Sara\",\"Ebu Talip ve Fatıma\",\"Yusuf ve Züleyha\"]},"
    "{\"category\":\"Hz. Muhammed\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Peygamberimiz nerede ve ne zaman doğmuştur?\","
    "\"correct_answer\":\"Mekke, 571 yılı, Rebiül Evvel ayının 17'si️\","
    "\"incorrect_answers\":[\"Mekke, 571 yılı, Rebiül Sani ayının 17'si\",\"Medine, 571 yılı, Rebiül Evvel ayının 17'si\",\"Medine, 571 yılı, Rebiül Sani ayının 17'si\"]},"
    "{\"category\":\"Hz. Muhammed\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Resulullah'ın dedesinin adı nedir?\","
    "\"correct_answer\":\"Abdulmuttalip️\","
    "\"incorrect_answers\":[\"Ebu Talip\",\"Abdullah\",\"Haşim \"]},"
    "{\"category\":\"Hz. Muhammed\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Peygamberimizin her daim yanında olan amcası ve aynı zamanda Hz.Ali'nin babası olan yüce insanın adı nedir? \","
    "\"correct_answer\":\"Ebu Talip️\","
    "\"incorrect_answers\":[\"Abdullah\",\"Abdulmuttalip\",\"Haşim \"]},"
    "{\"category\":\"Hz. Muhammed\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Peygamber Efendimizin süt annesinin adı nedir? \","
    "\"correct_answer\":\"Halime ️\","
    "\"incorrect_answers\":[\"Hamide ️\",\"Meryem\",\"Hatice \"]},"
    "{\"category\":\"Hz. Muhammed\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Peygamberimizin destekçi eşinin ve aynı zamanda Hz.Fatıma'nın annesi olan yüce hanımın adı nedir? \","
    "\"correct_answer\":\"Hatice ️\","
    "\"incorrect_answers\":[\"Maria\",\"Ümmü Seleme\",\"Ayşe \"]},"
    "{\"category\":\"Hz. Muhammed\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Peygamber efendimiz nereden nereye hicret etmiştir?\","
    "\"correct_answer\":\"Mekke'den Medine'ye\","
    "\"incorrect_answers\":[\"Medine'den Mekke'ye\",\"Mekke'den Şam'a\",\"Mekke'den Yemen'e \"]},"
    "{\"category\":\"Hz. Muhammed\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Efendimizin kabileler arasındaki sorunu çözerek Kabe'nin duvarına koyduğu taşın adı nedir? \","
    "\"correct_answer\":\"Hacer'ul Esved ️\","
    "\"incorrect_answers\":[\"Hacer'ul Beyza\",\"Yeşil taş\",\"Kırmızı taş \"]},"
    "{\"category\":\"Hz. Muhammed\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Hz. Muhammed'in peygamberlikle görevlendirilmesinden sonra ona ilk iman edenler kimlerdir? \","
    "\"correct_answer\":\"Ali ve Hatice ️\","
    "\"incorrect_answers\":[\"Ebu Bekir ve Ömer\",\"Osman ve Ebu Süfyan\",\"Ammar ve Hamza \"]},"
    "{\"category\":\"Hz. Muhammed\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Efendimizin son haccından dönerken Gadri Hum denilen yerde söylediği;  'Ben kimin mevlasıysam,... de onun mevlasıdır' sözünde noktalı yere hangi isim gelmelidir? \","
    "\"correct_answer\":\"Ali️\","
    "\"incorrect_answers\":[\"Ebu Bekir\",\"Ömer\",\"Osman\"]}]}";

var json2 = "{\"response_code\":0,\"results\":[{"
    "\"category\":\"Hz. Ali\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Hz. Ali nerede ve ne zaman doğmuştur?\","
    "\"correct_answer\":\"Kabenin içi, Bisetten 10 yıl önce, Recep ayının 13'ü\","
    "\"incorrect_answers\":[\"Medine, Bisetten 10 yıl önce, Recep ayının 13'ü\",\"Kufe, Bisetten 10 yıl önce, Recep ayının 13'ü\",\"Necef, Bisetten 10 yıl önce, Recep ayının 13'ü\"]},"
    "{\"category\":\"Hz. Ali\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Hz. Ali'nin babasının adı nedir?\","
    "\"correct_answer\":\"Ebu Talip \","
    "\"incorrect_answers\":[\"Abdullah\",\"Abdulmuttalip\",\"Hamza\"]},"
    "{\"category\":\"Hz. Ali\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Hz. Ali'nin annesi olan ve Peygamberimizin de onu annesi olarak yad ettiği değerli hanımın adı nedir?\","
    "\"correct_answer\":\"Fatıma binti Esed\","
    "\"incorrect_answers\":[\"Amine\",\"Hatice\",\"Meryem\"]},"
    "{\"category\":\"Hz. Ali\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Ali'yi kim şehit etmiştir?\","
    "\"correct_answer\":\"İbn Mülcem\","
    "\"incorrect_answers\":[\"Muaviye\",\"Ebu Süfyan\",\"Yezit\"]},"
    "{\"category\":\"Hz. Ali\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Hz. Ali'nin mübarek kabri nerededir?\","
    "\"correct_answer\":\"Irak'ın Necef şehri\","
    "\"incorrect_answers\":[\"Irak'ın Samarra şehri\",\"Irak'ın Kerbela şehri\",\"Irak'ın Kazımeyn şehri\"]},"
    "{\"category\":\"Hz. Ali\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İslam düşmanlarının her kabileden bir kişi olmak üzere Peygamber efendimizi öldürmek için geldiklerinde, canını ona feda ederek yatağında uyumayı kabul eden kimdir?\","
    "\"correct_answer\":\"Hz. Ali\","
    "\"incorrect_answers\":[\"Hz. Hamza\",\"Hz. Ebu Talip\",\"Hz. Ammar\"]},"
    "{\"category\":\"Hz. Ali\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Peygamber efendimizin buyurduğu üzere, hangi savaşta Hz. Ali'nin düşmana vurduğu bir kılıç darbesi, insan ve cinlerin tüm ibadetlerinden daha üstündür?\","
    "\"correct_answer\":\"Hendek\","
    "\"incorrect_answers\":[\"Uhud\",\"Bedir\",\"Hayber\"]},"
    "{\"category\":\"Hz. Ali\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Peygamber efendimizin Hz. Ali'yi Medine de kendi yerine bıraktığı ve Hz. Ali'nin katılmadığı tek savaş hangisidir?\","
    "\"correct_answer\":\"Tebük gazvesi \","
    "\"incorrect_answers\":[\"Hayber savaşı\",\"Bedir savaşı\",\"Uhud savaşı \"]},"
    "{\"category\":\"Hz. Ali\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Peygamber Efendimiz ensar ile muhacir arasında kardeşlik akdi okuyarak iki kişiyi birbiriyle kardeş ilan ettiği zaman kendisi kiminle kardeş olmuştur? \","
    "\"correct_answer\":\"Hz. Ali\","
    "\"incorrect_answers\":[\"Hz. Hamza\",\"Hz. Ammar\",\"Hz. Ebuzer \"]},"
    "{\"category\":\"Hz. Ali\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Hz. Ali kaç yaşında ve ne zaman şehit olmuştur? \","
    "\"correct_answer\":\"63 yaşında, Hicretin 40.yılı, Ramazan ayının 21'i\","
    "\"incorrect_answers\":[\"63 yaşında, Hicretin 50.yılı, Ramazan ayının 21'i\",\"63 yaşında, Hicretin 40. yılı, Sefer ayının 28'i\",\"63 Yaşında, Hicretin 50. yılı, Sefer ayının 28'i\"]}]}";

var json3 = "{\"response_code\":0,\"results\":[{"
    "\"category\":\"Hz. Fatıma\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Hz. Fatıma ne zaman ve nerede doğmuştur?\","
    "\"correct_answer\":\"Mekke, Bisetin 5. Yılı, Cemadiyessani ayı\","
    "\"incorrect_answers\":[\"Mekke, Bisetin 5. Yılı, Cemadiyulevvel ayı\",\"Medine, Bisetin 5.Yılı, Şaban ayı\",\"Medine, Bisetin 5. Yılı, Recep ayı\"]},"
    "{\"category\":\"Hz. Fatıma\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Resulullah'ın kızı Hz. Fatıma'nın annesinin adı nedir?\","
    "\"correct_answer\":\"Hz. Hatice\","
    "\"incorrect_answers\":[\"Hz. Halime\",\"Hz. Meryem\",\"Hz. Zeynep\"]},"
    "{\"category\":\"Hz. Fatıma\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Aşağıdakilerden hangisi Hz. Fatıma'nın lakaplarından birisi değildir?\","
    "\"correct_answer\":\"Masume\","
    "\"incorrect_answers\":[\"Tahire\",\"Zehra\",\"Betül\"]},"
    "{\"category\":\"Hz. Fatıma\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Aşağıdakilerden hangisi Hz. Hatice’nin Hz. Fatıma’yı doğurduğu zaman, ona yardım için gelenlerden biri değildir? \","
    "\"correct_answer\":\"Hz. Adem'in eşi Hz. Havva\","
    "\"incorrect_answers\":[\"Hz. İmran’ın kızı Hz. Meryem\",\"Hz. İbrahim’in eşi Hz. Sara\",\"Firavunun eşi Hz. Asiye\"]},"
    "{\"category\":\"Hz. Fatıma\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Bir fakir, Hz. Fatıma'nın evine geldiğinde Hz. Fatıma ona ne vermiştir? \","
    "\"correct_answer\":\"Düğün için olan yeni elbisesini\","
    "\"incorrect_answers\":[\"Bir külçe altın\",\"Bir miktar para\",\"Bir miktar yiyecek\"]},"
    "{\"category\":\"Hz. Fatıma\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Hz Fatıma'nın yardım amaçlı verdiği, bir fakirin ihtiyacını giderip, bir köleyi azad eden ve sonra tekrar sahibine dönen eşyası neydi? \","
    "\"correct_answer\":\"Gerdanlık\","
    "\"incorrect_answers\":[\"Yüzük\",\"Bilezik\",\"Küpe\"]},"
    "{\"category\":\"Hz. Fatıma\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Hz. Fatıma'nın hizmetçisinin adı nedir? \","
    "\"correct_answer\":\"Fizze\","
    "\"incorrect_answers\":[\"Gülsüm\",\"Kamber\",\"Seleme \"]},"
    "{\"category\":\"Hz. Fatıma\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Maide suresi 61.ayetin işaret ettiği, Peygamber efendimizin Hz. Ali, Hz. Fatıma, Hz. Hasan ve Hz. Hüseyin ile birlikte Allahın lanetinin yalancıların üzerine olması için dua edecekleri olayın adı nedir? \","
    "\"correct_answer\":\"Mubahale olayı\","
    "\"incorrect_answers\":[\"Hırre olayı\",\"Taif olayı\",\"Kerbela olayı \"]},"
    "{\"category\":\"Hz. Fatıma\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Aşağıdakilerden hangisi yemek yeme adaplarından biri değildir?\","
    "\"correct_answer\":\"Ayakta yemek yemek\","
    "\"incorrect_answers\":[\"Yemeğe bismillah ile başlamak\",\"Yemekten önce ellerimizi yıkamak\",\"Yemekten sonra Allaha şükretmek \"]},"
    "{\"category\":\"Hz. Fatıma\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Aşağıdakilerden hangisinde Hz. Fatıma'nın erkek çocuklarının ismi doğru verilmiştir? \","
    "\"correct_answer\":\"Hz. Hasan ve Hz. Hüseyin\","
    "\"incorrect_answers\":[\"Hz. Hasan ve Hz. Ali\",\"Hz. Ali ve Hz. Hüseyin\",\"Hz. Abbas ve Hz. Cafer\"]}]}";

var json4 = "{\"response_code\":0,\"results\":[{"
    "\"category\":\"Hz. Hasan\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hasan nerede ve ne zaman doğmuştur?\","
    "\"correct_answer\":\"Medine, Hicretin 3. yılı, Ramazan ayının 15'i\","
    "\"incorrect_answers\":[\"Mekke, Hicretin 3. yılı, Ramazan ayının 15'i\",\"Kufe, Hicretin 3. yılı, Ramazan ayının 15'i\",\"Necef, Hicretin 3. yılı, Ramazan ayının 15'i\"]},"
    "{\"category\":\"Hz. Hasan\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hasan'ın annesi ve babasının adları nelerdir? \","
    "\"correct_answer\":\"Hz. Fatıma ve Hz. Ali \","
    "\"incorrect_answers\":[\"Hz. Muhammed ve Hz. Hatice\",\"Hz. Abdullah ve Hz. Amine\",\"Hz. Ebu Talip ve Hz. Fatıma binti Esed\"]},"
    "{\"category\":\"Hz. Hasan\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Aşağıdakilerden hangisi İmam Hasan'ın lakaplarından birisidir?\","
    "\"correct_answer\":\"Müçteba\","
    "\"incorrect_answers\":[\"Şehitlerin efendisi\",\"Rıza\",\"Cevad\"]},"
    "{\"category\":\"Hz. Hasan\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hasan kaç yıl yaşamış ve imamlık yapmıştır?\","
    "\"correct_answer\":\"47 yıl yaşamış ve 10 yıl imamlık yapmıştır\","
    "\"incorrect_answers\":[\"57 yıl yaşamış ve 10 yıl imamlık yapmıştır\",\"47 yıl yalamış ve 20 yıl imamlık yapmıştır\",\"57 yıl yaşamış ve 20 yıl imamlık yapmıştır\"]},"
    "{\"category\":\"Hz. Hasan\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hasan'ı kim şehit etmiştir?\","
    "\"correct_answer\":\"Muaviyen'in planıyla eşi Cunde\","
    "\"incorrect_answers\":[\"Yezid'in planıyla eşi Cunde\",\"İbn Mulcem\",\"Hişam bin Abdulmelik\"]},"
    "{\"category\":\"Hz. Hasan\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Imam Hasan'ın mübarek kabri nerededir?\","
    "\"correct_answer\":\"Medine, Baki kabristanlığı\","
    "\"incorrect_answers\":[\"Mekke\",\"Kerbela\",\"Necef\"]},"
    "{\"category\":\"Hz. Hasan\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hasan kaç kere malının tamamını ve yarısını yoksullara bağışlamıştır?\","
    "\"correct_answer\":\"2 kere tamamını ve 3 kere yarısını\","
    "\"incorrect_answers\":[\"1 kere tamamını ve 2 kere yarısını\",\"1 kere tamamını ve 3 kere yarısını\",\"2 kere tamamını ve 1 kere yarısını\"]},"
    "{\"category\":\"Hz. Hasan\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hasan ve İmam Hüseyin'in yaşlı bir adamın yanlış yaptığı ve rahatsız olmayacağı bir şekilde düzeltikleri ameli hangisidir? \","
    "\"correct_answer\":\"Abdest almak \","
    "\"incorrect_answers\":[\"Namaz kılmak\",\"Hac ameli\",\"Zekat vermek \"]},"
    "{\"category\":\"Hz. Hasan\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hasan'ın babası Hz. Ali ile birlikte Muaviye'ye karşı yaptıkları savaşın adı nedir? \","
    "\"correct_answer\":\"Sıffin\","
    "\"incorrect_answers\":[\"Cemel\",\"Nehrevan\",\"Bedir \"]},"
    "{\"category\":\"Hz. Hasan\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hasan'dan sonra yerine geçen ve imametlik görevini üstlenen kardeşinin adı nedir? \","
    "\"correct_answer\":\"Hz. Hüseyin \","
    "\"incorrect_answers\":[\"Hz. Ali\",\"Hz. Zeynel Abidin\",\"Hz. Kasım\"]}]}";

var json5 = "{\"response_code\":0,\"results\":[{"
    "\"category\":\"Hz. Hüseyin\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Hz. Hüseyin nerede ve ne zaman doğmuştur?\","
    "\"correct_answer\":\"Medine, Hicretin 4.yılı, Şaban ayının 3'ü\","
    "\"incorrect_answers\":[\"Mekke,Hicretin 4.yılı, Şaban ayının 3'ü\",\"Necef, Hicretin 4.yılı, Şaban ayının 3'ü\",\"Kerbela, Hicretin 4.yılı, Şaban ayının 3'ü\"]},"
    "{\"category\":\"Hz. Hüseyin\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Aşağıdakilerden hangisi İmam Hüseyin'in en meşhur lakabıdır?\","
    "\"correct_answer\":\"Şehitlerin efendisi\","
    "\"incorrect_answers\":[\"Müçteba\",\"Hacetler kapısı\",\"Hadi\"]},"
    "{\"category\":\"Hz. Hüseyin\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hüseyin kimin askerleri tarafından şehit edilmiştir?\","
    "\"correct_answer\":\"Yezit\","
    "\"incorrect_answers\":[\"Muaviye\",\"Harun Reşit\",\"Mutevekkil\"]},"
    "{\"category\":\"Hz. Hüseyin\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hüseyin'in mübarek kabri nerededir?\","
    "\"correct_answer\":\"Irak, Kerbela şehri\","
    "\"incorrect_answers\":[\"Irak, Kazımeyn şehri\",\"İran, Meşhed şehri\",\"Irak, Necef şehri\"]},"
    "{\"category\":\"Hz. Hüseyin\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hüseyin(a.s)'ın vücudunun bereketiyle kanatları iyileşen meleğin adı nedir?\","
    "\"correct_answer\":\"Futrus\","
    "\"incorrect_answers\":[\"Cebrail\",\"Mikail\",\"İsrafil\"]},"
    "{\"category\":\"Hz. Hüseyin\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hüseyin Yezid'e biat etmeyip hangi şehir halkının davetini kabul etmiştir?\","
    "\"correct_answer\":\"Kufe\","
    "\"incorrect_answers\":[\"Meşhed\",\"Basra\",\"Yemen\"]},"
    "{\"category\":\"Hz. Hüseyin\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hüseyin'in önceden Kufe'ye gönderdiği ve Yezid'in askerleri tarafından şehit edilen amcasının oğlunun adı nedir?\","
    "\"correct_answer\":\"Müslim bin Akil\","
    "\"incorrect_answers\":[\"Süleyman\",\"Habib bin Mezahir\",\"Abdullah İbn Abbas\"]},"
    "{\"category\":\"Hz. Hüseyin\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Kerbela da tövbe edip İmam Hüseyine katılan komutan kimdir?\","
    "\"correct_answer\":\"Hür\","
    "\"incorrect_answers\":[\"Ömer İbn Sad\",\"İbn Ziyad\",\"Şimr\"]},"
    "{\"category\":\"Hz. Hüseyin\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Kerbela'da İmam Hüseyin'in 6 aylık oğlu Ali Asker'i okla vurarak şehit eden taş kaplli Yezid askerinin adı nedir?\","
    "\"correct_answer\":\"Hermele \","
    "\"incorrect_answers\":[\"Şimr\",\"Ömer İbn Sad\",\"İbn Ziyad\"]},"
    "{\"category\":\"Hz. Hüseyin\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Muharrem ayının 7. günü İbn Ziyad'ın emri ile İmam Hüseyin ve dostlarına yasaklanan şey nedir?\","
    "\"correct_answer\":\"Fırat nehrinin suyu\","
    "\"incorrect_answers\":[\"Yiyecek\",\"Namaz kılmaları\",\"Geri dönmeleri\"]}]}";

var json6 = "{\"response_code\":0,\"results\":[{"
    "\"category\":\"Hz. Ali\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Zeynel Abidin(a.s.) nerede ve ne zaman dünyaya gelmiştir?\","
    "\"correct_answer\":\"Medine, Hicretin 38. Yılı Şaban Ayının 5'i\","
    "\"incorrect_answers\":[\"Şam, Hicretin 45. Yılı Ramazan Ayının 3'ü\",\"Mekke, Hicretin 50. Yılı Recep Ayının 10'u\",\"Ebva, Hicretin 20. Yılı Muharrem Ayının 10'u\"]},"
    "{\"category\":\"İmam Zeynel Abidin(a.s.)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Zeynel Abidin(a.s.)'ın babası ve annesi kimdir?\","
    "\"correct_answer\":\"Hz.Hüseyin(a.s.) ve Şehribanu\","
    "\"incorrect_answers\":[\"Hz.Hasan(a.s.) ve Ümmü Eymen\",\"Hz.İbrahim(a.s.) ve Hz.Sara\",\"Hz.Cafer-i Sadık(a.s.) ve Hekime Hanım\"]},"
    "{\"category\":\"İmam Zeynel Abidin(a.s.)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Zeynel Abidin(a.s.) kaç yıl yaşamıştır?\","
    "\"correct_answer\":\"57 yıl\","
    "\"incorrect_answers\":[\"60 yıl\",\"45 yıl\",\"50 yıl\"]},"
    "{\"category\":\"İmam Zeynel Abidin(a.s.)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Zeynel Abidin(a.s.) her zaman sırtında torbalarla yardımı kimlere götürür ve onlara yardım ederdi?\","
    "\"correct_answer\":\"Muhtaç ve fakirlere\","
    "\"incorrect_answers\":[\"Zenginlere\",\"İslam Düşmanlarına\",\"Yöneticilere\"]},"
    "{\"category\":\"İmam Zeynel Abidin(a.s.)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Zeynel Abidin(a.s.) Kerbela'da neden savaşamadı?\","
    "\"correct_answer\":\"Hastalandığı için.\","
    "\"incorrect_answers\":[\"Mekke'de bulunduğu için.\",\"Kufe'ye gittiği için.\",\"Medine'de kaldığı için.\"]},"
    "{\"category\":\"İmam Zeynel Abidin(a.s.)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Kerbela olayından sonra Ehlibeyt'in kadınları ve çocukları İmam Zeynel Abidin ile birlikte nereye götürüldü?\","
    "\"correct_answer\":\"Şam şehrine\","
    "\"incorrect_answers\":[\"Medine şehrine\",\"Mekke şehrine\",\"Kufe şehrine\"]},"
    "{\"category\":\"İmam Zeynel Abidin(a.s.)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Yezit'in İmam Zeynel Abidin(a.s.)'a verdiği altın sikkeleri İmam ne yaptı?\","
    "\"correct_answer\":\"Fakirlere dağıttı\","
    "\"incorrect_answers\":[\"Yezit'e geri verdi\",\"Askerlere dağıttı\",\"Şam halkına dağıttı\"]},"
    "{\"category\":\"İmam Zeynel Abidin(a.s.)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Zeynel Abidin(a.s.)'ın dualarını barındıran, çok güzel ve önemli olan kitabın adı nedir?\","
    "\"correct_answer\":\"Sahife-i Seccadiye \","
    "\"incorrect_answers\":[\"Nehcül Belaga\",\"Kuran-ı Kerim\",\"Dular Kitabı\"]},"
    "{\"category\":\"İmam Zeynel Abidin(a.s.)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Zeynel Abidin(a.s.) neden şehit edilmiştir?\","
    "\"correct_answer\":\"İslam'ı savunup zalimlerle mücadele ettiği için\","
    "\"incorrect_answers\":[\"Hacca gittiği için\",\"Medine'de bulunduğu için\",\"Şam şehrine yolculuk yaptığı için\"]},"
    "{\"category\":\"İmam Zeynel Abidin(a.s.)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Zeynel Abidin(a.s.)'ın mübarek kabri nerededir.\","
    "\"correct_answer\":\"Baki Kabristanlığı, Medine\","
    "\"incorrect_answers\":[\"Nur Kabristanlığı, Mekke\",\"Mescid-i Nebevi, Medine\",\"Kerbela, Irak\"]}]}";

var json7 = "{\"response_code\":0,\"results\":[{"
    "\"category\":\"Hz. İmam Muhammed Bakır\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Bakır (as) nerede ve ne zaman doğmuştur? \","
    "\"correct_answer\":\"Medine, Hicretin 57. Yılı, Recep ayının 1'i\","
    "\"incorrect_answers\":[\"Medine, Hicretin 57. Yılı, Recep ayının 3'ü\",\"Mekke, Hicretin 57. Yılı, Recep ayının 1'i\",\"Mekke, Hicretin 57. Yılı, Recep ayının 3'ü\"]},"
    "{\"category\":\"Hz. İmam Muhammed Bakır\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Bakır kimin emri ile şehit edilmiştir? \","
    "\"correct_answer\":\"Hişam bin Abdulmelik \","
    "\"incorrect_answers\":[\"Mervan bin Hakem\",\"Abdulmelik bin Mervan\",\"Yezit bin Muaviye \"]},"
    "{\"category\":\"Hz. İmam Muhammed Bakır\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam'ın kabri nerededir? \","
    "\"correct_answer\":\"Medine, Baki kabristanlığı\","
    "\"incorrect_answers\":[\"Necef, vadius selam mezarlığı\",\"Kerbela\",\"Samarra \"]},"
    "{\"category\":\"Hz. İmam Muhammed Bakır\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam'ın annesinin  adı nedir? \","
    "\"correct_answer\":\"İmam Hasan'ın kızı Fatıma \","
    "\"incorrect_answers\":[\"İmam Kazım' ın kızı Masume\",\"İmam Ali'nin kızı Zeynep\",\"İmam Hadi'nin kızı Hekime \"]},"
    "{\"category\":\"Hz. İmam Muhammed Bakır\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Bakır kerbela da kaç yaşındaydı?\","
    "\"correct_answer\":\"4 yaşında\","
    "\"incorrect_answers\":[\"14 yaşında\",\"24 yaşında\",\"34 yaşında \"]},"
    "{\"category\":\"Hz. İmam Muhammed Bakır\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmamın en meşhur Lakabı olan bakırul ulumun anlamı nedir?\","
    "\"correct_answer\":\"İlimleri yaran \","
    "\"incorrect_answers\":[\"Hacetler kapısı\",\"Şifa kapısı\",\"Hikmet kapısı\"]},"
    "{\"category\":\"Hz. İmam Muhammed Bakır\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam'ın zamanına kadar yaşayan ve ona Peygamberin selamını ileten sahabe kimdir? \","
    "\"correct_answer\":\"Cabir bin Abdullah Ensari\","
    "\"incorrect_answers\":[\"Selmani Farsi\",\"Ebuzer Gaffari\",\"Ammar bin Yasir \"]},"
    "{\"category\":\"Hz. İmam Muhammed Bakır\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Bakır tıpkı namaz ve oruç gibi hangi ameli de ibadet olarak zikr ediyor?\","
    "\"correct_answer\":\"Çalışmak\","
    "\"incorrect_answers\":[\"Uyumak\",\"Yürümek\",\"Yemek yemek\"]},"
    "{\"category\":\"Hz. İmam Muhammed Bakır\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam'ın dostlarından birininin evine girmesine izin vermemesinin sebebi neydi?\","
    "\"correct_answer\":\"Düşman adamlarının orada bulunduğu için\","
    "\"incorrect_answers\":[\"Evde olmadığı için\",\"Sefere çıkmaya hazırlandığı için\",\"Müsait olmadığı için \"]},"
    "{\"category\":\"Hz. İmam Muhammed Bakır\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Bakır kaç yaşına kadar yaşadı ve kaç yıl imamlık yaptı?\","
    "\"correct_answer\":\"57 yıl yaşadı, 19 yıl imamlık yaptı\","
    "\"incorrect_answers\":[\"67 yıl yaşadı, 25 yıl imamlık yaptı\",\"47 yıl yaşadı, 15 yıl imamlık yaptı\",\"60 yıl yaşadı, 19 yıl imamlık yaptı\"]}]}";

var json8 = "{\"response_code\":0,\"results\":[{"
    "\"category\":\"İmam Cafer-i Sadık(a.s.)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Cafer-i Sadık(a.s.) nerede ve ne zaman dünyaya gelmiştir?\","
    "\"correct_answer\":\"Medine, Hicretin 83. Yılı Rebiülevvel ayının 17'si\","
    "\"incorrect_answers\":[\"Mekke, Hicretin 55. Yılı, Ramazan ayının 3'ü\",\"Şam, Hicretin 90. Yılı, Muharrem Ayının 10'u\",\"Kufe, Hicretin 45. Yılı, Recep Ayının 25'i\"]},"
    "{\"category\":\"İmam Cafer-i Sadık(a.s.)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Cafer-i Sadık(a.s.)'ın babasının ve annesinin adı nedir?\","
    "\"correct_answer\":\"İmam Muhammed Bakır(a.s.) ve Ümmü Furuh\","
    "\"incorrect_answers\":[\"İmam Rıza(a.s.) ve Ümmü Eymen\",\"Hz.Hüseyin(a.s.) ve Leyla Hanım\",\"Hz.Cevad(a.s.) ve Ümmü Ebiha\"]},"
    "{\"category\":\"İmam Cafer-i Sadık(a.s.)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Cafer-i Sadık(a.s.), ömrü boyunca her fırsatta ne yapmıştır?\","
    "\"correct_answer\":\"İslam'ın yayılıp halka ulaşması alanında çaba harcamıştır\","
    "\"incorrect_answers\":[\"Makam ve mevki elde etmeye çalışmıştır.\",\"Ailesi ve akrabalarına makam edinmek için çalışmıştır.\",\"Servet biriktirmek için çalışmıştır\"]},"
    "{\"category\":\"İmam Cafer-i Sadık(a.s.)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Cafer-i Sadık(a.s.), kendi döneminde halkı aydınlatıyordu. Bunu hangi alanda ve nasıl yapıyordu?\","
    "\"correct_answer\":\"İlim alanında ve öğrenci yetiştirerek\","
    "\"incorrect_answers\":[\"Tarlada çalışarak\",\"Devletin başındaki Mensur'a itaati önererek\",\"İnsanları Şam şehrine seyahate teşvik ederek \"]},"
    "{\"category\":\"İmam Cafer-i Sadık(a.s.)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Cafer-i Sadık(a.s.) döneminde hangi grup arasında yönetimi ele geçirmek için çatışma ve çekişme vardı?\","
    "\"correct_answer\":\"Emeviler ile Abbasiler\","
    "\"incorrect_answers\":[\"Haşimiler ile Bedeviler\",\"Osmaniler ile Mekkeliler\",\"Rumlar ile Moğollar\"]},"
    "{\"category\":\"İmam Cafer-i Sadık(a.s.)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Cafer-i Sadık(a.s.), yemesi için getirilen yemeği neden hemen yemedi ve cehennemi hatırladı?\","
    "\"correct_answer\":\"Yemeğin çok sıcak olmasından dolayı\","
    "\"incorrect_answers\":[\"Yemeği beğenmediği için\",\"Yemeğin kokusu olmadığı için\",\"Yemek az olduğu için\"]},"
    "{\"category\":\"İmam Cafer-i Sadık(a.s.)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Cafer-i Sadık(a.s.), Mensur Devanegi'nin düzenlediği yemek sofrasından neden kalkıp gitti?\","
    "\"correct_answer\":\"Yemek sofrasına haram olan bir içki getirdikleri için\","
    "\"incorrect_answers\":[\"Canı sıkıldığı için\",\"Yemekleri beğenmediği için\",\"Evden çağırdıkları için\"]},"
    "{\"category\":\"İmam Cafer-i Sadık(a.s.)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Hangi küçük hayvan zalim bir hükümdar ve halife olan Mensur Devanegi'yi rahatsız etmiştir?\","
    "\"correct_answer\":\"Küçük Sinek\","
    "\"incorrect_answers\":[\"Karınca\",\"Serçe kuşu\",\"Beyaz Kedi\"]},"
    "{\"category\":\"İmam Cafer-i Sadık(a.s.)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Cafer-i Sadık(a.s.)'ı kim ve nasıl şehadet etmiştir?\","
    "\"correct_answer\":\"Mensur Devanigi, zehirle şehit etmiştir\","
    "\"incorrect_answers\":[\"Hallac adlı kişi okla şehit etmiştir\",\"Hermele adlı kişi kılıçla şehit etmiştir\",\"Yezit, zindana atarak şehit etmiştir\"]},"
    "{\"category\":\"İmam Cafer-i Sadık(a.s.)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Cafer-i Sadık(a.s.)'ın mübarek kabri nerededir?\","
    "\"correct_answer\":\"Baki Kabristanlığı, Medine\","
    "\"incorrect_answers\":[\"Aile Kabristanlığı, Mekke\",\"Kufe Mescidi, Irak\",\"Kerbela, Irak\"]}]}";

var json9 = "{\"response_code\":0,\"results\":[{"
    "\"category\":\"Hz. Musa Kazım\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Musa Kazım(as) nerede ve ne zaman doğmuştur?\","
    "\"correct_answer\":\"Ebva, Hicretin 128.yılı, Sefer ayının 7'si\","
    "\"incorrect_answers\":[\"Ebva,Hicretin 138.yılı,Sefer ayının 5'i\",\"Medine, Hicretin 128.yılı, Sefer ayının 7'si\",\"Mekke, Hicretin 138.yılı, Sefer ayının 5'i\"]},"
    "{\"category\":\"Hz. Musa Kazım\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Musa Kazım(as) kim tarafından şehit edilmiştir? \","
    "\"correct_answer\":\"Harun Reşit \","
    "\"incorrect_answers\":[\"Metevekkil\",\"Yezit\",\"Abdulmelik \"]},"
    "{\"category\":\"Hz. Musa Kazım\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam'ın kabri nerededir? \","
    "\"correct_answer\":\"Kazımeyn \","
    "\"incorrect_answers\":[\"Necef\",\"Kerbela\",\"Mekke\"]},"
    "{\"category\":\"Hz. Musa Kazım\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam'ın lakaplarından biri olan Kazım ne demektir? \","
    "\"correct_answer\":\"Öfkesini yenen\","
    "\"incorrect_answers\":[\"Cömert\",\"Yüce\",\"Pak ve temiz\"]},"
    "{\"category\":\"Hz. Musa Kazım\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Musa Kazım'ın annesinin adı nedir? \","
    "\"correct_answer\":\"Hamide\","
    "\"incorrect_answers\":[\"Amine\",\"Nergis\",\"Şehribanu\"]},"
    "{\"category\":\"Hz. Musa Kazım\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam'ın babel hevaic lakabının anlamı nedir? \","
    "\"correct_answer\":\"Hacetler kapısı\","
    "\"incorrect_answers\":[\"Şifalar kapısı\",\"Hikmet kapısı\",\"İlim kapısı\"]},"
    "{\"category\":\"Hz. Musa Kazım\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmamın kerameti ile perde de  resmi olan ve sonra canlanan hayvan hangisi? \","
    "\"correct_answer\":\"Aslan\","
    "\"incorrect_answers\":[\"Geyik\",\"Ceylan\",\"Kartal \"]},"
    "{\"category\":\"Hz. Musa Kazım\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Harun Reşidin İmam Kazıma vermek istediği , Peygamberimizin kızı Hz.Fatıma'ya hediye ettiği bağın adı?\","
    "\"correct_answer\":\"Fedek\","
    "\"incorrect_answers\":[\"Hayber\",\"Beni Haşim\",\"Bağdat\"]},"
    "{\"category\":\"Hz. Musa Kazım\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Musa Kazım'ın kızının adı nedir?\","
    "\"correct_answer\":\"Hz. Masume\","
    "\"incorrect_answers\":[\"Hz. Zeynep\",\"Hz. Zehra\",\"Hz. Meryem\"]},"
    "{\"category\":\"Hz. Musa Kazım\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam'ın kızının mübarek kabri nerededir?\","
    "\"correct_answer\":\"İran, Kum şehri\","
    "\"incorrect_answers\":[\"İran, Meşhed şehri\",\"Irak, Kerbela şehri\",\"Irak, Necef şehri\"]}]}";

var json10 = "{\"response_code\":0,\"results\":[{"
    "\"category\":\"Hz. İmam Rıza\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Rıza nerede ve ne zaman doğmuştur? \","
    "\"correct_answer\":\"Medine, Hicretin 148.yılı, Zilkade ayının 11'i\","
    "\"incorrect_answers\":[\"Medine, Hicretin 138.yılı, Zilhicce ayının 11'i\",\"Meşhed, Hicretin 148.yılı, Zilkade ayının 11'i\",\"Kufe, Hicretin 148.yılı, Zilkade ayının 11'i\"]},"
    "{\"category\":\"Hz. İmam Rıza\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Rıza'nın annesinin adı nedir? \","
    "\"correct_answer\":\"Hz. Necme\","
    "\"incorrect_answers\":[\"Hz. Masume\",\"Hz. Zehra\",\"Hz. Zeynep\"]},"
    "{\"category\":\"Hz. İmam Rıza\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmamın Rıza lakabının anlamı nedir? \","
    "\"correct_answer\":\"Razı olmak\","
    "\"incorrect_answers\":[\"Sabırlı olmak\",\"Cömert olmak\",\"Cesur olmak \"]},"
    "{\"category\":\"Hz. İmam Rıza\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Rıza kim tarafından şehit edilmiştir? \","
    "\"correct_answer\":\"Memun\","
    "\"incorrect_answers\":[\"Emin\",\"Harun Reşit\",\"Mervan\"]},"
    "{\"category\":\"Hz. İmam Rıza\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam'ın kabri nerede bulunmaktadır? \","
    "\"correct_answer\":\"İran, Meşhed şehri\","
    "\"incorrect_answers\":[\"Irak, Necef şehri\",\"Suudi Arabistan, Medine şehri\",\"Irak, kerbela şehri\"]},"
    "{\"category\":\"Hz. İmam Rıza\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Abbasi Halifesi Memun imam Rıza'yı zorla Medine'den nereye götürtmüştür? \","
    "\"correct_answer\":\"Horasan\","
    "\"incorrect_answers\":[\"Kufe\",\"Kerbela\",\"Şam\"]},"
    "{\"category\":\"Hz. İmam Rıza\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Memun İmam Rıza'yı Medine'den zorla getirtip, çirkin planını gerçekleştirmek için İmam'a ne teklif etmiştir?\","
    "\"correct_answer\":\"Halifelik veya veliahtlik\","
    "\"incorrect_answers\":[\"Medine valiliği\",\"Vezirlik\",\"Mekke valiliği \"]},"
    "{\"category\":\"Hz. İmam Rıza\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Hz. Hamide'ye rüyasında oğlu İmam Kazım'ı Necme Hatun ile evlelendirmesini kim söylemiştir?\","
    "\"correct_answer\":\"Hz. Resulullah\","
    "\"incorrect_answers\":[\"Hz. İmam Rıza\",\"Hz. Hüseyin\",\"Hz. Sadık \"]},"
    "{\"category\":\"Hz. İmam Rıza\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Imam Rıza'nın halk ile birlikte çöle gidip ettiği ve ardından kabul olan duası nedir?\","
    "\"correct_answer\":\"Yağmur duası\","
    "\"incorrect_answers\":[\"Şifa duası\",\"Kazanç duası\",\"Belalardan korunma duası \"]},"
    "{\"category\":\"Hz. İmam Rıza\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Rıza kaç yaşında şehit edilmiştir? \","
    "\"correct_answer\":\"55 yaşında\","
    "\"incorrect_answers\":[\"50 yaşında\",\"60 yaşında\",\"45 yaşında\"]}]}";

var json11 = "{\"response_code\":0,\"results\":[{"
    "\"category\":\"Hz. Muhammed Tagi\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Muhammed Cevad (as) ne zaman ve nerede doğmuştur?\","
    "\"correct_answer\":\"Medine, hicretin 195.yılı, recep ayının 10'u\","
    "\"incorrect_answers\":[\"Medine, hicretin 185.yılı, şaban ayının 10'u\",\"Mekke, Hicretin 195.yılı, recep ayının 10'u\",\"Bağdat, Hicretin 195.yılı,şaban ayının 10'u\"]},"
    "{\"category\":\"Hz. Muhammed Tagi\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Cevad(as) Kim tarafından şehit edilmiştir?\","
    "\"correct_answer\":\"Mutasım\","
    "\"incorrect_answers\":[\"Memun\",\"Harun Reşid\",\"Muaviye \"]},"
    "{\"category\":\"Hz. Muhammed Tagi\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam'ın kabri nerededir?\","
    "\"correct_answer\":\"Kazımeyn\","
    "\"incorrect_answers\":[\"Medine\",\"Mekke\",\"Kerbela \"]},"
    "{\"category\":\"Hz. Muhammed Tagi\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam'ın lakabı Cevad'ın anlamı nedir?\","
    "\"correct_answer\":\"Cömert\","
    "\"incorrect_answers\":[\"Cesur\",\"Sabırlı\",\"Mütevazı \"]},"
    "{\"category\":\"Hz. Muhammed Tagi\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Cevad'ı çocuk yaşta İmam seçen Allahın çocuk yaşta peygamberlik ile görevlendirdiği elçileri hangileridir? \","
    "\"correct_answer\":\"Hz. İsa ve Hz. Yahya\","
    "\"incorrect_answers\":[\"Hz. İbrahim ve Hz Yusuf\",\"Hz. Musa ve Hz. Harun\",\"Hz. Adem ve Hz. Nuh \"]},"
    "{\"category\":\"Hz. Muhammed Tagi\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Kundakta insanlarla konuşan Peygamber hangisidir? \","
    "\"correct_answer\":\"Hz. İsa\","
    "\"incorrect_answers\":[\"Hz. Yakup\",\"Hz. Muhammed\",\"Hz. İsmail \"]},"
    "{\"category\":\"Hz. Muhammed Tagi\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Cevad'ın Zindandan kurtardığı babasının sadık dosdu olan kişi hangisidir? \","
    "\"correct_answer\":\"Ebaselt\","
    "\"incorrect_answers\":[\"Hişam\",\"Cafer\",\"İbn Akil \"]},"
    "{\"category\":\"Hz. Muhammed Tagi\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Cevad'ın vesilesi ile şifa bulan adamın rahatsızlığı neydi?\","
    "\"correct_answer\":\"Gözleri görmüyordu\","
    "\"incorrect_answers\":[\"Sağırdı\",\"Yürüyemiyordu\",\"Felçti\"]},"
    "{\"category\":\"Hz. Muhammed Tagi\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Imam Cevad'ın imamlığını ispatlamak için bir Müslümana gösterdiği keramet neydi?\","
    "\"correct_answer\":\"Asasının konuşması\","
    "\"incorrect_answers\":[\"Bir ölüyü diriltmesi\",\"Bir hayvanla konuşması\",\"Asasının yılana dönüşmesi \"]},"
    "{\"category\":\"Hz. Muhammed Tagi\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Memun döneminde İmam Cevad'ı küçük düşürmek için getirilen ilim adamının adı nedir? \","
    "\"correct_answer\":\"Yahya\","
    "\"incorrect_answers\":[\"Musa\",\"Ahmed\",\"Abbas\"]}]}";

var json12 = "{\"response_code\":0,\"results\":[{"
    "\"category\":\"İmam Hadi(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hadi(a.s) nerede ve ne zaman dünyaya gelmiştir?\","
    "\"correct_answer\":\"Medine, Hicretin 212. yılı Zilhicce ayının 15'i \","
    "\"incorrect_answers\":[\"Mekke, Hicretin 200. yılı Recep ayının 12'si\",\"Kufe, Hicretin 190. yılı Ramazan ayının 10'u \",\"Kerbela, Hicretin 210. yılı Zilkade ayının 15'i \"]},"
    "{\"category\":\"İmam Hadi(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hadi(a.s)'ın babasının ve annesinin adı nedir?\","
    "\"correct_answer\":\"İmam Muhammed Taki(a.s) ve Hz.Semane\","
    "\"incorrect_answers\":[\"İmam Bakır(a.s) ve Hz.Asiye\",\"İmam Cafer-i Sadık(a.s) ve Hz.Zeyneb\",\"İmam Rıza(a.s) ve Hz.Gülsüm\"]},"
    "{\"category\":\"İmam Hadi(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hadi(a.s), hangi devletin zamanında yaşamıştır?\","
    "\"correct_answer\":\"Abbasiler\","
    "\"incorrect_answers\":[\"Emeviler\",\"Osmaniler\",\"Fatimiler\"]},"
    "{\"category\":\"İmam Hadi(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hadi(a.s), hangi kralın sorularını cevaplayarak Müslüman olmasını sağlamıştır?\","
    "\"correct_answer\":\"Roma kralı\","
    "\"incorrect_answers\":[\"Irak kralı\",\"Suriye kralı\",\"İran kralı\"]},"
    "{\"category\":\"İmam Hadi(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hadi(a.s), kime bulunmayan bir ilacı göndererek iyileşmesinde yardım etmiştir?\","
    "\"correct_answer\":\"Hasta olan sahabesine\","
    "\"incorrect_answers\":[\"Canı sıkılan bakkalcıya\",\"Yolda kalan yolcuya\",\"Sağlıklı yaşlı bir kadına\"]},"
    "{\"category\":\"İmam Hadi(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hadi(a.s), kime ve ne için endişelenmemesini söyledi?\","
    "\"correct_answer\":\"Yunus adındaki dostuna, kırdığı mücevher için\","
    "\"incorrect_answers\":[\"Hasan adındaki dostuna, yüzük kaybettiği için\",\"Cafer adındaki dostuna, para kaybettiği için \",\"Rıdvan adındaki dostuna, hacca gidemediği için\"]},"
    "{\"category\":\"İmam Hadi(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hadi(a.s), Mütevekkil tarafından İslami çalışmaları kısıtlanması için hangi şehre zorla götürüldü?\","
    "\"correct_answer\":\"Samarra\","
    "\"incorrect_answers\":[\"Kerbela \",\"Necef\",\"Meşhed\"]},"
    "{\"category\":\"İmam Hadi(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Abbasi hükümdarı Mütevekkil, İmam'ın insanlarla ilişkisini kısıtlamak istiyordu. Neden bunu yapmıştır?\","
    "\"correct_answer\":\"İnsanların İmam'dan etkilenip İslam'a yakınlaşmasını istemiyordu \","
    "\"incorrect_answers\":[\"İmam'ın dinlenmesini istiyordu\",\"İnsanları çok seviyordu \",\"İmam'ın rahat çalışmasını istiyordu \"]},"
    "{\"category\":\"İmam Hadi(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hadi(a.s), kim tarafından şehit edilmiştir?\","
    "\"correct_answer\":\"Abbasi Devleti halifesi Mutez\","
    "\"incorrect_answers\":[\"Emevi Devleti halifesi Yezit\",\"Emevi Devleti halifesi Ömer bin Abdülaziz \",\"Abbasi Devleti halifesi Memun\"]},"
    "{\"category\":\"İmam Hadi(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hadi(a.s)'ın mübarek kabri nerededir?\","
    "\"correct_answer\":\"Samarra Şehri, Irak \","
    "\"incorrect_answers\":[\"Kerbela Şehri, Irak\",\"Medine Şehri \",\"Necef Şehri, Irak\"]}]}";

var json13 = "{\"response_code\":0,\"results\":[{"
    "\"category\":\"İmam Hasan Askeri(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hasan Askeri(a.s), nerede ve ne zaman dünyaya gelmiştir?\","
    "\"correct_answer\":\"Medine, Hicretin 232. Yılı \","
    "\"incorrect_answers\":[\"Mekke, Hicretin 220. Yılı\",\"Mekke, Hicretin 210. Yılı\",\"Samarra, Hicretin 232. Yılı\"]},"
    "{\"category\":\"İmam Hasan Askeri(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hasan Askeri(a.s)'ın babasının ve annesinin adı nedir?\","
    "\"correct_answer\":\"İmam Hadi ve Hz.Hadise\","
    "\"incorrect_answers\":[\"İmam Cevad ve Hz.Sümeyye\",\"İmam Ali ve Hz.Fatıma\",\"İmam Rıza ve Hz.Melike\"]},"
    "{\"category\":\"İmam Hasan Askeri(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"'Gerçek Müslüman, başkalarına karşı mütevazı ve alçak gönüllü davranan ve onlara her zaman yardım edendir'. İmam(a.s) bu sözüne uymak istesek ne yapmalıyız?\","
    "\"correct_answer\":\"Başkalarına her zaman saygı duymalı ve onlara yardım etmeliyiz.\","
    "\"incorrect_answers\":[\"Sadece kendimize yardım etmemiz yeterlidir.\",\"Alçak gönüllü olmasak daha iyi olur.\",\"Başkalarına karşı kırıcı olmalıyız.\"]},"
    "{\"category\":\"İmam Hasan Askeri(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hasan Askeri(a.s), tıpkı diğer imamlar gibi her dili biliyor ve konuşuyordu. Aynı zamanda her ilmi de biliyordu. İmam bu özelliğini nereden almıştır?\","
    "\"correct_answer\":\"Allah tarafından İmam'a verilmiştir.\","
    "\"incorrect_answers\":[\"İmam, çevreden öğrenmiştir.\",\"İmam, okulda öğrenmiştir.\",\"Okuldaki tüm hocalar İmam'a ders vermiştir. \"]},"
    "{\"category\":\"İmam Hasan Askeri(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hasan Askeri(a.s)'ın askeri lakabı nereden gelmiştir?\","
    "\"correct_answer\":\"İmam, askerlerin bulunduğu bir bölgede kaldığı için bu lakabı almıştır.\","
    "\"incorrect_answers\":[\"İmam, askerleri çok sevdiği için verilmiştir.\",\"Askerlerle yolculuğa çıktığı için verilmiştir. \",\"İmam'ın asker arkadaşı olduğu için bu lakabı almıştır.\"]},"
    "{\"category\":\"İmam Hasan Askeri(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hasan Askeri(a.s), daha güzel bir yaşam için neler yapmayı önermiştir?\","
    "\"correct_answer\":\"Her işimizde Allah'ı hatırlamayı, Kuran-ı Kerim okumayı ve Peygamber Efendimize salavat göndermeyi önermiştir.\","
    "\"incorrect_answers\":[\"Okulda bolca yaramazlık yapmayı önermiştir.\",\"Eve geç saatte gelmeyi önermiştir.\",\"Fazla yemek yemeği önermiştir.\"]},"
    "{\"category\":\"İmam Hasan Askeri(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hasan Askeri(a.s), kaç yıl imamlık görevini yerine getirmiştir?\","
    "\"correct_answer\":\"6 yıl\","
    "\"incorrect_answers\":[\"16 yıl\",\"20 yıl\",\"24 yıl\"]},"
    "{\"category\":\"İmam Hasan Askeri(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hasan Askeri(a.s), kaç yaşında şehit edilmiştir?\","
    "\"correct_answer\":\"28 yaşında\","
    "\"incorrect_answers\":[\"39 yaşında\",\"45 yaşında\",\"53 yaşında\"]},"
    "{\"category\":\"İmam Hasan Askeri(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hasan Askeri(a.s), ne zaman şehit edilmiştir?\","
    "\"correct_answer\":\"Hicretin 260. yılı, Rebiyy'ul Evvel ayının 8'i\","
    "\"incorrect_answers\":[\"Hicretin 230. yılı, Ramazan ayının 5'i\",\"Hicretin 220. yılı, Recep ayının 25'i \",\"Hicretin 250. yılı, Şaban ayının 15'i\"]},"
    "{\"category\":\"İmam Hasan Askeri(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hasan Askeri(a.s)'ın mübarek kabri nerededir?\","
    "\"correct_answer\":\"Samarra Şehri, Irak\","
    "\"incorrect_answers\":[\"Necef Şehri, Irak\",\"Kerbela Şehri, Irak \",\"Meşhed Şehri, İran\"]}]}";

var json14 = "{\"response_code\":0,\"results\":[{"
    "\"category\":\"Hz. Mehdi(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Hz. Mehdi(a.s) nerede ve ne zaman doğmuştur?\","
    "\"correct_answer\":\"Samarra, Hicretin 255. yılı, Şaban ayının 15'i\","
    "\"incorrect_answers\":[\"Medine, Hicretin 255. yılı, Şaban ayının 15'i\",\"Mekke, Hicretin 255. yılı, Şaban ayının 15'i\",\"Kazımeyn, Hicretin 255. yılı, Şaban ayının 15'i\"]},"
    "{\"category\":\"Hz. Mehdi(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam-ı Zaman'ın annesinin adı nedir?\","
    "\"correct_answer\":\"Hz. Nergis\","
    "\"incorrect_answers\":[\"Hz. Şehribanu\",\"Hz. Fatıma\",\"Hz. Hekime\"]},"
    "{\"category\":\"Hz. Mehdi(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Aşağıdakilerden hangisi İmam-ı Zaman’ın lakaplarından birisi değildir?\","
    "\"correct_answer\":\"Rıza\","
    "\"incorrect_answers\":[\"Bagiyyetullah\",\"Mehdi\",\"Höccet \"]},"
    "{\"category\":\"Hz. Mehdi(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Mehdi’nin annesi Hz.Nergis hangi peygamberin havirelerinden birinin neslindendir? \","
    "\"correct_answer\":\"Hz. İsa\","
    "\"incorrect_answers\":[\"Hz. Musa\",\"Hz. İbrahim\",\"Hz. Muhammed \"]},"
    "{\"category\":\"Hz. Mehdi(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hadi'nin kız kardeşi ve İmam Hasan Askeri'nin halasının adı nedir? \","
    "\"correct_answer\":\"Hekime\","
    "\"incorrect_answers\":[\"Halime\",\"Zeynep\",\"Hatice \"]},"
    "{\"category\":\"Hz. Mehdi(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Hasan Askeri'nin dostlarından ve İran'ın Kum şehrinden yaşamış kişi kimdir? \","
    "\"correct_answer\":\"Ahmed bin İshak\","
    "\"incorrect_answers\":[\"Ebaselt\",\"Ammar bin Yasir\",\"Ebuzer Geffari\"]},"
    "{\"category\":\"Hz. Mehdi(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Mehdi’nin gaybeti (gizlenmesi) kaç kısma ayrılır? \","
    "\"correct_answer\":\"İki kısma; küçük(suğra) gaybet ve büyük(kubra) gaybet\","
    "\"incorrect_answers\":[\"Üç kısma; küçük, orta ve büyük gaybet\",\"Bir kısma; büyük gaybet\",\"Bir kısma; küçük gaybet\"]},"
    "{\"category\":\"Hz. Mehdi(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Aşağıdakilerden hangisi İmam Mehdi’nin gaybeti döneminde yapmamız gereken şeylerden birisi değildir? \","
    "\"correct_answer\":\"Hiç birşey yapmadan beklemek\","
    "\"incorrect_answers\":[\"İslamın emirlerine uymak\",\"Düşmanın hilelerine karşı mücadele etmek\",\"Hz. Mehdi’nin zuhurunu(gelmesini) istemek\"]},"
    "{\"category\":\"Hz. Mehdi(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"Aşağıdakilerden hangisi İmam Mehdi’nin dostlarının özelliklerinden birisi değildir? \","
    "\"correct_answer\":\"Onlar tembel ve korkaktırlar\","
    "\"incorrect_answers\":[\"Onların tek hedefi Allah'ın rızası ve hoşnutluğudur\",\"Hem Allah onları sever hem de onlar Allah'ı sever\",\"İslam düşmanlarına karşı cesurdurlar\"]},"
    "{\"category\":\"Hz. Mehdi(a.s)\",\"type\":\"multiple\",\"difficulty\":\"easy\","
    "\"question\":\"İmam Mehdi geldiğinde insanların ahlakları güzelleşecektir ve birbirleriyle güzel şekilde yaşacaklardır. Aşağıdakilerden hangisi bu güzel ahlaklardan değildir?\","
    "\"correct_answer\":\"Yalan konuşacaklar\","
    "\"incorrect_answers\":[\"Birbirlerine yardım edecekler\",\"Kimse birbirini üstün görmeyecek\",\"Herkes kardeşlik içinde yaşayacak\"]}]}";
